### ISSUE TITLE
ImportError: libta_lib.so.0

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#1813]
I hav efreshly installed FT via WSL, no errors during installation, but I cannot manage to run a backtest

### Relevant code exceptions or logs:

  ```
(.env) andreas@LAPTOP-RE2H6OSI:~/freqtrade$ ./freqtrade/main.py -s test_strategy backtesting --refresh-pairs-cached
Traceback (most recent call last):
  File "./freqtrade/main.py", line 14, in <module>
    from freqtrade.worker import Worker
  File "/home/andreas/freqtrade/freqtrade/worker.py", line 14, in <module>
    from freqtrade.freqtradebot import FreqtradeBot
  File "/home/andreas/freqtrade/freqtrade/freqtradebot.py", line 18, in <module>
    from freqtrade.edge import Edge
  File "/home/andreas/freqtrade/freqtrade/edge/__init__.py", line 16, in <module>
    from freqtrade.optimize import get_timeframe
  File "/home/andreas/freqtrade/freqtrade/optimize/__init__.py", line 11, in <module>
    from freqtrade.optimize.default_hyperopt import DefaultHyperOpts  # noqa: F401
  File "/home/andreas/freqtrade/freqtrade/optimize/default_hyperopt.py", line 3, in <module>
    import talib.abstract as ta
  File "/home/andreas/freqtrade/.env/lib/python3.6/site-packages/talib/__init__.py", line 43, in <module>
    from ._ta_lib import (
ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory
(.env) andreas@LAPTOP-RE2H6OSI:~/freqtrade$ python -V
  ```

**Comment by xmatthias** [comment]
how did you install?

ta-lib needs to be installed following the instructions.
the step you're missing (or maybe got an error) is on [installing ta-lib](https://www.freqtrade.io/en/latest/installation/#1-install-ta-lib).

It does however work fine on WSL.

**Comment by Prossi79** [comment]
Oh okay, I was thinking that this is included in the installation routine  :)  ... but yes it is mentioned in the SW requirements. Is there any way to include it in the autoinstallation as it is done wth Python?

Software requirements¶

    Python 3.6.x
    pip (pip3)
    git
    TA-Lib
    virtualenv (Recommended)
    Docker (Recommended)

**Comment by xmatthias** [comment]
well, it's installed when you run the `setup.sh` script.

it is a pure C library, so installing it with pip is not possible, sorry.

**Comment by Prossi79** [comment]
installed TALib according the documentation, still the same problem 

(strange, as it is working on my VPS Ubuntu machine, not on the WSL one)

**Comment by xmatthias** [comment]
if you install TALib after the python modules, you'll need to run "pip3 install TA-Lib==0.4.17` again, otherwise it won't see the modules...

**Comment by Prossi79** [comment]
hello again, still struggeling :(

I checked the /usr/local ... libta_* files are there

here the log:

"
Run the bot !
-------------------------
You can now use the bot by executing 'source .env/bin/activate; python freqtrade'.
(.env) andreas@LAPTOP-RE2H6OSI:~/freqtrade$ python ./freqtrade/main.py -s APstrat1 backtesting --refresh-pairs-cached
Traceback (most recent call last):
  File "./freqtrade/main.py", line 14, in <module>
    from freqtrade.worker import Worker
  File "/home/andreas/freqtrade/freqtrade/worker.py", line 14, in <module>
    from freqtrade.freqtradebot import FreqtradeBot
  File "/home/andreas/freqtrade/freqtrade/freqtradebot.py", line 18, in <module>
    from freqtrade.edge import Edge
  File "/home/andreas/freqtrade/freqtrade/edge/__init__.py", line 16, in <module>
    from freqtrade.optimize import get_timeframe
  File "/home/andreas/freqtrade/freqtrade/optimize/__init__.py", line 11, in <module>
    from freqtrade.optimize.default_hyperopt import DefaultHyperOpts  # noqa: F401
  File "/home/andreas/freqtrade/freqtrade/optimize/default_hyperopt.py", line 3, in <module>
    import talib.abstract as ta
  File "/home/andreas/.env/lib/python3.6/site-packages/talib/__init__.py", line 43, in <module>
    from ._ta_lib import (
ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory
(.env) andreas@LAPTOP-RE2H6OSI:~/freqtrade$ cd ..
(.env) andreas@LAPTOP-RE2H6OSI:~$ pip3 install TA-Lib==0.4.17
Requirement already satisfied: TA-Lib==0.4.17 in ./.env/lib/python3.6/site-packages (0.4.17)
Requirement already satisfied: numpy in ./.env/lib/python3.6/site-packages (from TA-Lib==0.4.17) (1.16.3)

"

**Comment by Prossi79** [comment]
hello again, still struggeling :(
I checked the /usr/local ... libta_* files are there
here the log after a freshly installed FT

`(.env) andreas@LAPTOP-RE2H6OSI:~/freqtrade$ cd ..
(.env) andreas@LAPTOP-RE2H6OSI:~$ pip3 install TA-Lib==0.4.17
Requirement already satisfied: TA-Lib==0.4.17 in ./.env/lib/python3.6/site-packages (0.4.17)
Requirement already satisfied: numpy in ./.env/lib/python3.6/site-packages (from TA-Lib==0.4.17) (1.16.3)
(.env) andreas@LAPTOP-RE2H6OSI:~$ cd freqtrade
(.env) andreas@LAPTOP-RE2H6OSI:~/freqtrade$ python ./freqtrade/main.py -s APstrat1 backtesting --refresh-pairs-cached
Traceback (most recent call last):
  File "./freqtrade/main.py", line 14, in <module>
    from freqtrade.worker import Worker
  File "/home/andreas/freqtrade/freqtrade/worker.py", line 14, in <module>
    from freqtrade.freqtradebot import FreqtradeBot
  File "/home/andreas/freqtrade/freqtrade/freqtradebot.py", line 18, in <module>
    from freqtrade.edge import Edge
  File "/home/andreas/freqtrade/freqtrade/edge/__init__.py", line 16, in <module>
    from freqtrade.optimize import get_timeframe
  File "/home/andreas/freqtrade/freqtrade/optimize/__init__.py", line 11, in <module>
    from freqtrade.optimize.default_hyperopt import DefaultHyperOpts  # noqa: F401
  File "/home/andreas/freqtrade/freqtrade/optimize/default_hyperopt.py", line 3, in <module>
    import talib.abstract as ta
  File "/home/andreas/.env/lib/python3.6/site-packages/talib/__init__.py", line 43, in <module>
    from ._ta_lib import (
ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory
(.env) andreas@LAPTOP-RE2H6OSI:~/freqtrade$`

**Comment by vapor99** [comment]
Same problem here exactly.  Fresh Ubuntu 18.10 on a home server.  This is on the development branch.

╰─$ python freqtrade                             
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "freqtrade/__main__.py", line 11, in <module>
    from freqtrade import main
  File "/home/pez/dev/freqtrade/freqtrade/main.py", line 14, in <module>
    from freqtrade.worker import Worker
  File "/home/pez/dev/freqtrade/freqtrade/worker.py", line 14, in <module>
    from freqtrade.freqtradebot import FreqtradeBot
  File "/home/pez/dev/freqtrade/freqtrade/freqtradebot.py", line 18, in <module>
    from freqtrade.edge import Edge
  File "/home/pez/dev/freqtrade/freqtrade/edge/__init__.py", line 16, in <module>
    from freqtrade.optimize import get_timeframe
  File "/home/pez/dev/freqtrade/freqtrade/optimize/__init__.py", line 11, in <module>
    from freqtrade.optimize.default_hyperopt import DefaultHyperOpts  # noqa: F401
  File "/home/pez/dev/freqtrade/freqtrade/optimize/default_hyperopt.py", line 3, in <module>
    import talib.abstract as ta
  File "/home/pez/dev/freqtrade/.env/lib/python3.6/site-packages/talib/__init__.py", line 43, in <module>
    from ._ta_lib import (
ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory

**Comment by fachos** [comment]
hi... try edit .bashrc  "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"

**Comment by xmatthias** [comment]
I assume this is solved now.
Feel free to reopen if you think otherwise

**Comment by qkum** [comment]
>" if you install TALib after the python modules, you'll need to run "pip3 install TA-Lib==0.4.17` again, otherwise it won't see the modules..."

Thanks! You can not imagen how many hours people are using struggling to figure out to use open source software. Thank god we got windows. Without them noone would own a pc in 2020. Or 2030.

**Comment by qkum** [comment]
> hi... try edit .bashrc "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"

And the command to do that is:
 $ vi ~/.bashrc 

Because if we were experts enough to know that command in the head we would not ask for help to start with. Remember that. Now I helped 25+ people by writing this silly command. And prevented 25 more threads like this.

**Comment by hroff-1902** [comment]
> 25+ helped

"335..." (c)
(We have a movie, where an army recruiting officer answered "335..." to a question from a rookie, will they give him guns and ammos... 🤣 )

**Comment by pd420** [comment]
Hi , i am getting the same error , but i dont get anything from the above comments , i tried everything , but still getting same error, can anyone give a step by ste[ guidance, it would be a big help

**Comment by xmatthias** [comment]
@pd420 the original error was simply that the ta-lib C dependency was not installed.
If the error is the same, your problem will be the same as well.

I'd however ask you to not revive old issues, everyone in this issue will be notified as part of that (and i'll therefore lock this issue now).
