### ISSUE TITLE
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000176968D85E0>

### ISSUE THREAD

**Issue by Mo7mud** [freqtrade/freqtrade#7422]
## Describe your environment

Operating system: Windows 10
Python Version: Python 3.10.0
CCXT version: couldn't get it
Freqtrade Version: 2022.8
  
I get this exception when I start the bot

  ```
 2022-09-16 09:33:59,583 - freqtrade.freqtradebot - INFO - Updating 0 open orders.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000176968D85E0>
Traceback (most recent call last):
  File "C:\Users\Mohammad\miniconda3\envs\freqtrade-conda\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Mohammad\miniconda3\envs\freqtrade-conda\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Mohammad\miniconda3\envs\freqtrade-conda\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\Mohammad\miniconda3\envs\freqtrade-conda\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
  ```
And it's repeated about 12 times in a row.

Bot is running though and I can't notice anything unnormal but I thought I should let you know about it and maybe there is something broken but I didn't notice.

It doesn't happen all the time.

I'm using KuCoin exchange.

Other log that I don't understand is this : 
`freqtrade.wallets - WARNING - Minimum stake amount > available balance. 17.655 > 7.010052030000004`

This appeared after setting `available_capital` to 100

And there is no trades since then, there were some trades with stake amount more than $100 but now there's one trade with stake amount $56, should I restart the bot to sync the wallet or it isn't necessary?

**Comment by xmatthias** [comment]
>  Minimum stake amount > available balance. 17.655 > 7.010052030000004

this simply means that your strategy/configuration tried to open a trade for 17$ - where the available balance is only 7$. You can check the balance with `/balance` via telegram to see where that capital went.

available_capital  obviously has a play in this - as it'll define the initial capital. The actual position size is then calculated either through stake_amount, custom_stake_amount - or when unlimited, by dividing the current (assumed) balance by max_open_trades.

---

The crash itself seems to be an issue with the python version used (3.10.0) - and shows as fixed in the python repositories (https://github.com/python/cpython/issues/83413, https://github.com/python/cpython/issues/92841).
Since 3.10.0 was released in 2021 - but the bug was fixed in 2022 - it's clearly not included in your version.

best update to the latest 3.10 version (3.10.7 at this point in time) and retry.

**Comment by Mo7mud** [comment]
This is my config : 
```
  "dry_run": false,
    "max_open_trades": 6,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "available_capital": 100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "force_entry_enable": true,
    "trading_mode": "spot",
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "entry": 15,
        "exit": 15,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "limit",
        "force_entry": "limit",
        "force_exit": "limit",
        "stoploss": "limit",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60
    },
    "entry_pricing": {
        "price_side": "other",
        "use_order_book": false,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": { "enabled": false, "bids_to_ask_delta": 1 }
    },
    "exit_pricing": {
        "price_side": "other",
        "use_order_book": false,
        "order_book_top": 1,
        "price_last_balance": 0.0
    },
```

The balance on exchange is over $200 and I'm still getting the warning and no trades open when entry occurs.

For python version I'll update and let you know the result.

**Comment by xmatthias** [comment]
available_capital=100 - so from the 200 on the exchange, you give the bot 100 (it'll assume the remaining 100$are not present).

you then split the 100 into 6 chunks - so you're at ~20$per position.

Now if you got an open position of 56$ - so the whole calculation changes / becomes messed up- so you'll get the remaining 44$ / 5 (max_open_trades-1) - which will result in a stake < 10$.

**Comment by Mo7mud** [comment]
So the issue in that open trade.
OK I'll wait until it exits and see.
Another question, is there any option to send notification to telegram bot when an entry occurs?
I mean send msg like coin name and entry price.

**Comment by xmatthias** [comment]
you'll get these notifications if you have configured [telegram](https://www.freqtrade.io/en/stable/telegram-usage/).

you can control which messages [via the configuration](https://www.freqtrade.io/en/stable/telegram-usage/#control-telegram-noise).

**Comment by Mo7mud** [comment]
After updating python version I get this error:
`freqtrade.commands.trade_commands - ERROR - No module named 'fastapi'`

```
2022-09-16 19:20:21,730 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
2022-09-16 19:20:21,913 - freqtrade.commands.trade_commands - ERROR - No module named 'fastapi'
2022-09-16 19:20:21,914 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "E:\freqtrade\freqtrade\commands\trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "E:\freqtrade\freqtrade\worker.py", line 35, in __init__
    self._init(False)
  File "E:\freqtrade\freqtrade\worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "E:\freqtrade\freqtrade\freqtradebot.py", line 82, in __init__
    self.rpc: RPCManager = RPCManager(self)
  File "E:\freqtrade\freqtrade\rpc\rpc_manager.py", line 46, in __init__
    from freqtrade.rpc.api_server import ApiServer
  File "E:\freqtrade\freqtrade\rpc\api_server\__init__.py", line 2, in <module>
    from .webserver import ApiServer
  File "E:\freqtrade\freqtrade\rpc\api_server\webserver.py", line 7, in <module>
    from fastapi import Depends, FastAPI
ModuleNotFoundError: No module named 'fastapi'
```
Why?

I ran through a lot of issues and solved them but this one I don't know how to solve.

**Comment by Mo7mud** [comment]
@xmatthias any help

**Comment by xmatthias** [comment]
well you didn't install properly - your dependencies are not installed.

**Comment by Mo7mud** [comment]
> well you didn't install properly - your dependencies are not installed.

Solved it by creating a new conda env and installed the bot again

**Comment by xmatthias** [comment]
has the new environment the same error (Proactor exceptions), or is it gone now?

**Comment by Mo7mud** [comment]
> has the new environment the same error (Proactor exceptions), or is it gone now?

First conda latest python version available is 3.10.4 and it has the issue unfortunately so after creating a new conda env with python 3.10.4 the crash happened again.
So I used venv with python 3.10.7.
I didn't see it again since I used python 3.10.7 but as I said at first it doesn't happen all the time, so till now it's gone.
If anything happened I'll let you know for sure.
Thank you for the follow up.
