### ISSUE TITLE
Errors on _rpc_trade_status after orders on Kucoin

### ISSUE THREAD

**Issue by tferreira** [freqtrade/freqtrade#7757]
## Describe your environment

  * Operating system: `Ubuntu 22.04`
  * Python Version: `3.10.6`
  * CCXT version: `ccxt==2.1.82`
  * Freqtrade Version: `2022.11.dev-9ee478ade`
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Hi. I have been running a new install of Freqtrade a couple days ago, using the `develop` branch.
Just after doing a `forcebuy (market order)` (also happened with a `forcesell (market order)` later on), I immediately started getting HTTP 500 errors on `/status` when looking at requests made by FreqUI on my browser. FreqUI gets stuck, displaying the bot as unreacheable with the red dot on the header.

Please note that this issue happens with bots using the `Kucoin` exchange.

```
2022-11-16 22:17:20,874 - uvicorn.access - INFO - 127.0.0.1:33776 - "GET /api/v1/status HTTP/1.0" 500
2022-11-16 22:17:20,898 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
[...]
  File "/home/ubuntu/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 97, in status
    return rpc._rpc_trade_status()
  File "/home/ubuntu/freqtrade/freqtrade/rpc/rpc.py", line 221, in _rpc_trade_status
    open_order='({} {} rem={:.8f})'.format(
TypeError: unsupported format string passed to NoneType.__format__
```

### Steps to reproduce:

  1. Run a Freqtrade bot on the `develop` branch using `Kucoin` exchange.
  2. Execute a forcebuy (market order) while having FreqUI running.
  3. Having Freqtrade logs at `info` level, stacktrace of `NoneType` errors can be seen, HTTP 500 `/status` requests, while FreqUI is stuck.
  
### Observed Results:

Please note that these errors are likely to still happen for some time even after restarting Freqtrade, when getting HTTP 429 (rate limit) from Kucoin (happens quite often with this exchange). So orders might not be fetched and updated right away, causing the issue to keep happening.

It seems to be happening since the following commit https://github.com/freqtrade/freqtrade/commit/7c84edbc23cb9018f423c095336bdb70938447c0, and originally caused by `ccxt` when calling Kucoin API:
An issue opened on `ccxt` library GH regarding "Kucoin Spot Market Orders" raises the fact that the `Order` object may have some of his fields as `None` when creating a market order, because they are missing from Kucoin API response: https://github.com/ccxt/ccxt/issues/14634

One of the maintainers of `ccxt` suggests to use ccxt's `fetchOrder` to get the data afterwards and have the fully updated order. This is actually what was done on commit https://github.com/freqtrade/freqtrade/commit/7c84edbc23cb9018f423c095336bdb70938447c0 before, thus updating the order when calling `/status`.

Reverting the commit and starting the bot fixes the issue as soon as `/status` gets called by FreqUI.

Thank you for your help.

### Relevant code exceptions or logs

Pasting the full stacktrace here:

```
2022-11-16 22:17:20,017 - uvicorn.access - INFO - 127.0.0.1:33764 - "GET /api/v1/show_config HTTP/1.0" 200
2022-11-16 22:17:20,874 - uvicorn.access - INFO - 127.0.0.1:33776 - "GET /api/v1/status HTTP/1.0" 500
2022-11-16 22:17:20,898 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntu/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 97, in status
    return rpc._rpc_trade_status()
  File "/home/ubuntu/freqtrade/freqtrade/rpc/rpc.py", line 221, in _rpc_trade_status
    open_order='({} {} rem={:.8f})'.format(
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by xmatthias** [comment]
Kucoin is not an officially supported exchange for a reason (their api is too instable to reliably support them).


please provide us with logs from your bot with `log_responses` set to true (in the exchange section of the configuration).
That will log the responses kucoin is actually giving. As you correctly point out - their info is often missing / incomplete

**Comment by tferreira** [comment]
Thank you for your answer.

Here are the logs when doing a force entry market order:
```
2022-11-17 10:52:24,245 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for SHIB/USDT with stake_amount: 9.709183176 ...
2022-11-17 10:52:24,357 - freqtrade.exchange.exchange - INFO - API create_order: {'id': '637593d8a4a3f900019ce0d1', 'clientOrderId': '78c40b2c-7843-4491-94d5-8271a8e92c38', 'info': {'orderId': '637593d8a4a3f900019ce0d1'}, 'timestamp': 1668649944357, 'datetime': '2022-11-17T01:52:24.357Z', 'lastTradeTimestamp': None, 'symbol': 'SHIB/USDT', 'type': 'market', 'side': 'buy', 'price': None, 'amount': 1055345.9973, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': None}
2022-11-17 10:52:24,366 - freqtrade.freqtradebot - INFO - Order #637593d8a4a3f900019ce0d1 was created for SHIB/USDT and status is None.
```

And then doing a force exit:
```
2022-11-17 11:03:19,083 - freqtrade.exchange.exchange - INFO - API create_order: {'id': '63759667da4d6c000144ef71', 'clientOrderId': '10703fab-a42b-4ec2-a6e1-f8234ca69503', 'info': {'orderId': '63759667da4d6c000144ef71'}, 'timestamp': 1668650599083, 'datetime': '2022-11-17T02:03:19.083Z', 'lastTradeTimestamp': None, 'symbol': 'SHIB/USDT', 'type': 'market', 'side': 'sell', 'price': None, 'amount': 1055345.9973, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': None}
2022-11-17 11:03:20,078 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 509, 'exchange': 'Kucoin', 'pair': 'SHIB/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 9.19e-06, 'order_rate': 9.19e-06, 'order_type': 'market', 'amount': 1055345.9973, 'open_rate': 9.2e-06, 'close_rate': 9.19e-06, 'current_rate': 9.19e-06, 'profit_amount': -0.02996127, 'profit_ratio': -0.00308279, 'buy_tag': 'force_entry', 'enter_tag': 'force_entry', 'sell_reason': 'force_exit', 'exit_reason': 'force_exit', 'open_date': datetime.datetime(2022, 11, 17, 1, 52, 24, 381659), 'close_date': datetime.datetime(2022, 11, 17, 2, 3, 20, 78455), 'stake_amount': 9.70918317516, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2022-11-17 11:03:20,327 - freqtrade.wallets - INFO - Wallets synced.
2022-11-17 11:03:20,341 - uvicorn.access - INFO - 127.0.0.1:49182 - "POST /api/v1/forcesell HTTP/1.0" 200
2022-11-17 11:03:21,972 - uvicorn.access - INFO - 127.0.0.1:54164 - "GET /api/v1/status HTTP/1.0" 500
```

Edit: Just noticed it also happens with limit orders made by the bot.

**Comment by xmatthias** [comment]
it'll be interesting to see when the error happens.
the force exit won't cause any error based on the log (all fields are filled as expected) - and is therefore irrelevant.

The market order **might** - however the log is too short for that to determine for sure (we do have handling for this in place, as this is a known problem with kucoin).

I'll need the log from the api response up to the exception to actually start looking at this.

**Comment by tferreira** [comment]
> the force exit won't cause any error based on the log (all fields are filled as expected) - and is therefore irrelevant.

Couldn't it be cause the `remaining` field is also `None` on the API response? As per the log above, it actually caused an HTTP 500 too on `/status` just after, and logs are just filled with the same errors afterwards. 

Here is the complete output:
```
2022-11-17 11:03:17,142 - uvicorn.access - INFO - 127.0.0.1:54152 - "GET /api/v1/status HTTP/1.0" 200
2022-11-17 11:03:18,606 - uvicorn.access - INFO - 127.0.0.1:54162 - "OPTIONS /api/v1/forcesell HTTP/1.0" 200
2022-11-17 11:03:18,875 - freqtrade.wallets - INFO - Wallets synced.
2022-11-17 11:03:19,083 - freqtrade.exchange.exchange - INFO - API create_order: {'id': '63759667da4d6c000144ef71', 'clientOrderId': '10703fab-a42b-4ec2-a6e1-f8234ca69503', 'info': {'orderId': '63759667da4d6c000144ef71'}, 'timestamp': 1668650599083, 'datetime': '2022-11-17T02:03:19.083Z', 'lastTradeTimestamp': None, 'symbol': 'SHIB/USDT', 'type': 'market', 'side': 'sell', 'price': None, 'amount': 1055345.9973, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': None}
2022-11-17 11:03:20,078 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 509, 'exchange': 'Kucoin', 'pair': 'SHIB/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 9.19e-06, 'order_rate': 9.19e-06, 'order_type': 'market', 'amount': 1055345.9973, 'open_rate': 9.2e-06, 'close_rate': 9.19e-06, 'current_rate': 9.19e-06, 'profit_amount': -0.02996127, 'profit_ratio': -0.00308279, 'buy_tag': 'force_entry', 'enter_tag': 'force_entry', 'sell_reason': 'force_exit', 'exit_reason': 'force_exit', 'open_date': datetime.datetime(2022, 11, 17, 1, 52, 24, 381659), 'close_date': datetime.datetime(2022, 11, 17, 2, 3, 20, 78455), 'stake_amount': 9.70918317516, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2022-11-17 11:03:20,327 - freqtrade.wallets - INFO - Wallets synced.
2022-11-17 11:03:20,341 - uvicorn.access - INFO - 127.0.0.1:49182 - "POST /api/v1/forcesell HTTP/1.0" 200
2022-11-17 11:03:21,972 - uvicorn.access - INFO - 127.0.0.1:54164 - "GET /api/v1/status HTTP/1.0" 500
2022-11-17 11:03:21,984 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntu/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 97, in status
    return rpc._rpc_trade_status()
  File "/home/ubuntu/freqtrade/freqtrade/rpc/rpc.py", line 221, in _rpc_trade_status
    open_order='({} {} rem={:.8f})'.format(
TypeError: unsupported format string passed to NoneType.__format__
```

Sorry for the truncated logs earlier, I wasn't sure the rest was actually relevant. Here is a complete example for entry too:
```
2022-11-17 16:37:43,057 - uvicorn.access - INFO - 127.0.0.1:51806 - "GET /api/v1/status HTTP/1.0" 200
2022-11-17 16:37:46,363 - freqtrade.wallets - INFO - Wallets synced.
2022-11-17 16:37:46,448 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for TWT/USDT with stake_amount: 9.707441855099999 ...
2022-11-17 16:37:46,669 - freqtrade.exchange.exchange - INFO - API create_order: {'id': '6375e4ca420be4000138e866', 'clientOrderId': '8c232e16-449b-49f2-8fbd-aa032c1d15f3', 'info': {'orderId': '6375e4ca420be4000138e866'}, 'timestamp': 1668670666669, 'datetime': '2022-11-17T07:37:46.669Z', 'lastTradeTimestamp': None, 'symbol': 'TWT/USDT', 'type': 'market', 'side': 'buy', 'price': None, 'amount': 4.4447, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': None}
2022-11-17 16:37:46,676 - freqtrade.freqtradebot - INFO - Order #6375e4ca420be4000138e866 was created for TWT/USDT and status is None.
2022-11-17 16:37:46,813 - freqtrade.wallets - INFO - Wallets synced.
2022-11-17 16:37:46,870 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 511, 'type': entry, 'buy_tag': 'force_entry', 'enter_tag': 'force_entry', 'exchange': 'Kucoin', 'pair': 'TWT/USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 2.184, 'open_rate': 2.184, 'order_type': 'market', 'stake_amount': 9.707441855099999, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 4.4447, 'open_date': datetime.datetime(2022, 11, 17, 7, 37, 46, 678322), 'current_rate': 2.184, 'sub_trade': False}
2022-11-17 16:37:46,915 - uvicorn.access - INFO - 127.0.0.1:51810 - "POST /api/v1/forcebuy HTTP/1.0" 200
2022-11-17 16:37:47,932 - uvicorn.access - INFO - 127.0.0.1:33430 - "GET /api/v1/trades?limit=500 HTTP/1.0" 200
2022-11-17 16:37:49,380 - uvicorn.access - INFO - 127.0.0.1:35426 - "GET /api/v1/trades?limit=500&offset=500 HTTP/1.0" 200
2022-11-17 16:37:51,650 - uvicorn.access - INFO - 127.0.0.1:59040 - "GET /api/v1/show_config HTTP/1.0" 200
2022-11-17 16:37:52,149 - uvicorn.access - INFO - 127.0.0.1:35442 - "GET /api/v1/status HTTP/1.0" 500
2022-11-17 16:37:52,158 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntu/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 97, in status
    return rpc._rpc_trade_status()
  File "/home/ubuntu/freqtrade/freqtrade/rpc/rpc.py", line 221, in _rpc_trade_status
    open_order='({} {} rem={:.8f})'.format(
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by xmatthias** [comment]
should be fixed with the last commit.

**Comment by tferreira** [comment]
Thank you for the fix, there is indeed no more errors in the logs.

However it doesn't seem to update correctly after a sell. Even though it's a market order and filled immediately on the exchange, 15 minutes later I still see the trade in FreqUI with the `*` next to the pair name, until I eventually hit the refresh button so that it triggers a `fetch_order` and updates it.

**Comment by xmatthias** [comment]
nothing in the UI (other than a forcesell)  triggers a "fetch_order" call to the exchange.

best make sure you don't have auto-updates disabled in the UI.

**Comment by tferreira** [comment]
Thanks again for your support and having investigated this issue.

I do have "Background sync" enabled in the UI. Indeed as the refresh button just does a call to `/status` it's probably unrelated.
Not sure if it can help improve anything, but just in case, here is what I experienced:

I did a forcesell, around 2022-11-18 23:20:33 local time:
```
2022-11-18 23:20:33,430 - uvicorn.access - INFO - 127.0.0.1:59412 - "OPTIONS /api/v1/forcesell HTTP/1.0" 200
2022-11-18 23:20:33,574 - freqtrade.wallets - INFO - Wallets synced.
2022-11-18 23:20:33,759 - uvicorn.access - INFO - 127.0.0.1:59424 - "GET /api/v1/show_config HTTP/1.0" 200
2022-11-18 23:20:33,790 - freqtrade.exchange.exchange - INFO - API create_order: {'id': '637794b1da5ae900012a58c8', 'clientOrderId': 'dd248f1b-7dca-4a9d-985e-c1e36a346c7f', 'info': {'orderId': '637794b1da5ae900012a58c8'}, 'timestamp': 1668781233790, 'datetime': '2022-11-18T14:20:33.790Z', 'lastTradeTimestamp': None, 'symbol': 'APE/USDT', 'type': 'market', 'side': 'sell', 'price': None, 'amount': 3.2137, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': None}
2022-11-18 23:20:33,902 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 513, 'exchange': 'Kucoin', 'pair': 'APE/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 3.0135, 'order_rate': 3.0135, 'order_type': 'market', 'amount': 3.2137, 'open_rate': 3.0287, 'close_rate': 3.0135, 'current_rate': 3.0135, 'profit_amount': -0.06826606, 'profit_ratio': -0.00700663, 'buy_tag': 'force_entry', 'enter_tag': 'force_entry', 'sell_reason': 'force_exit', 'exit_reason': 'force_exit', 'open_date': datetime.datetime(2022, 11, 18, 14, 16, 50, 321200), 'close_date': datetime.datetime(2022, 11, 18, 14, 20, 33, 902459), 'stake_amount': 9.73333319, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2022-11-18 23:20:33,951 - freqtrade.wallets - INFO - Wallets synced.
2022-11-18 23:20:33,957 - uvicorn.access - INFO - 127.0.0.1:36302 - "POST /api/v1/forcesell HTTP/1.0" 200
```

In between, no relevant logs.. though about 15 mins later:
```
2022-11-18 23:33:13,034 - uvicorn.access - INFO - 127.0.0.1:42664 - "GET /api/v1/show_config HTTP/1.0" 200
2022-11-18 23:33:13,107 - uvicorn.access - INFO - 127.0.0.1:34806 - "GET /api/v1/locks HTTP/1.0" 200
2022-11-18 23:33:14,706 - freqtrade.exchange.exchange - INFO - API fetch_order: {'id': '637794b1da5ae900012a58c8', 'clientOrderId': 'dd248f1b-7dca-4a9d-985e-c1e36a346c7f', 'symbol': 'APE/USDT', 'type': 'market', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'sell', 'amount': 3.2137, 'price': 3.0144, 'stopPrice': 0.0, 'cost': 9.68737728, 'filled': 3.2137, 'remaining': 0.0, 'timestamp': 1668781233747, 'datetime': '2022-11-18T14:20:33.747Z', 'fee': {'currency': 'USDT', 'cost': 0.00968737728}, 'status': 'closed', 'info': {'id': '637794b1da5ae900012a58c8', 'symbol': 'APE-USDT', 'opType': 'DEAL', 'type': 'market', 'side': 'sell', 'price': '0', 'size': '3.2137', 'funds': '0', 'dealFunds': '9.68737728', 'dealSize': '3.2137', 'fee': '0.00968737728', 'feeCurrency': 'USDT', 'stp': '', 'stop': '', 'stopTriggered': False, 'stopPrice': '0', 'timeInForce': 'GTC', 'postOnly': False, 'hidden': False, 'iceberg': False, 'visibleSize': '0', 'cancelAfter': 0, 'channel': 'API', 'clientOid': 'dd248f1b-7dca-4a9d-985e-c1e36a346c7f', 'remark': None, 'tags': 'partner:ccxt', 'isActive': False, 'cancelExist': False, 'createdAt': 1668781233747, 'tradeType': 'TRADE'}, 'lastTradeTimestamp': None, 'average': 3.0144, 'trades': [], 'fees': [{'currency': 'USDT', 'cost': 0.00968737728}]}
2022-11-18 23:33:14,712 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=513, pair=APE/USDT, amount=3.21370000, is_short=False, leverage=1.0, open_rate=3.02870000, open_since=2022-11-18 14:16:50)
2022-11-18 23:33:14,853 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=513, pair=APE/USDT, amount=3.21370000, is_short=False, leverage=1.0, open_rate=3.02870000, open_since=2022-11-18 14:16:50) [sell]: 0.0096873773 USDT - rate: 0.001
2022-11-18 23:33:14,858 - freqtrade.persistence.trade_model - INFO - Updating trade (id=513) ...
2022-11-18 23:33:14,864 - freqtrade.persistence.trade_model - INFO - MARKET_SELL has been fulfilled for Trade(id=513, pair=APE/USDT, amount=3.21370000, is_short=False, leverage=1.0, open_rate=3.02870000, open_since=2022-11-18 14:16:50).
2022-11-18 23:33:14,870 - freqtrade.persistence.trade_model - INFO - Marking Trade(id=513, pair=APE/USDT, amount=3.21370000, is_short=False, leverage=1.0, open_rate=3.02870000, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2022-11-18 23:33:15,039 - freqtrade.wallets - INFO - Wallets synced.
2022-11-18 23:33:15,134 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit_fill, 'trade_id': 513, 'exchange': 'Kucoin', 'pair': 'APE/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 3.0144, 'order_rate': 3.0144, 'order_type': '', 'amount': 3.2137, 'open_rate': 3.0287, 'close_rate': 3.0144, 'current_rate': None, 'profit_amount': -0.06537662, 'profit_ratio': -0.00671007, 'buy_tag': 'force_entry', 'enter_tag': 'force_entry', 'sell_reason': 'force_exit', 'exit_reason': 'force_exit', 'open_date': datetime.datetime(2022, 11, 18, 14, 16, 50, 321200), 'close_date': datetime.datetime(2022, 11, 18, 14, 33, 14, 870104), 'stake_amount': 9.73333319, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': -0.06537662}
```

**Comment by xmatthias** [comment]
from afar - it would suggest that the order only filled at that point.
