### ISSUE TITLE
Custom Exit question

### ISSUE THREAD

**Issue by infiniteneurotech** [freqtrade/freqtrade#8808]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: 3.10.7 (`python -V`)
  * CCXT version: 2.4.60  (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.12 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello, I'm trying to create a custom exit to automatically exit once the profit percent exceeds the trade open rate + the ATR at trade open. I've read through the documentation, searched previous questions and looked at other examples. I couldn't find the exact solution but from what I read I've come up with this code:

```
def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                        current_profit: float, **kwargs):
            dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
            last_candle = dataframe.iloc[-1].squeeze()

            trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
            trade_candle = dataframe.loc[dataframe['date'] == trade_date]
            # trade_candle may be empty for trades that just opened as it is still incomplete.
            if not trade_candle.empty:
                trade_candle = trade_candle.squeeze()

            profit_target = trade_candle['ATR']/trade.open_rate

            # sell when profit exceeds target
            if (current_profit > profit_target):
                return 'take_profit'
```
When I backtest the strategy it appears as though the custom exit is working, but I get a warning saying freqtrade.strategy.strategy_wrapper - WARNING - Strategy caused the following exception: The truth value of a Series is ambiguous <bound method strategy.custom_exit

So my questions are:

Is there a problem with using current profit > profit_target that's causing the warning? If so, what would you suggest instead? I'd like to get rid of the warning as it repeats over and over in the terminal. 
Where in the documentation is the info about the trade object attributes? Eg trade.open_rate, trade.stoploss etc? I've seen links to the advanced strategy docs from other answers on here, but can't find the info in there. Is this just general Python knowledge or specific to Freqtrade?

Thanks, I would really appreciate any help

**Comment by xmatthias** [comment]
First off, I think the remaining part after the "if" should be moved into the if statement.

if that doesn't hit, then the candle won't be squeezed, probably resulting in a series for ATR (even though an empty series).

---

Aside from that, i'd strongly recommend to update to a more recent version - we don't provide support for versions that are several months old - so it's very well possible that some issues were fixed around this (best read the changelog, i don't remember from the top of my head).

**Comment by infiniteneurotech** [comment]
Thanks for your reply. I updated Freqtrade to the latest version, which didn't fix the warning message but needed to be done regardless. I didn't realise I was using such an old version as I did a fresh install on a new machine only 2 months ago - I must have used an old Docker image. 

Changing the if statement did fix the problem however, so thanks for that. Here's the code (which I think is now correct!):

```
def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                        current_profit: float, **kwargs):
            dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
            last_candle = dataframe.iloc[-1].squeeze()

            trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
            trade_candle = dataframe.loc[dataframe['date'] == trade_date]
            # trade_candle may be empty for trades that just opened as it is still incomplete.
            if not trade_candle.empty:
                trade_candle = trade_candle.squeeze()
                profit_target = trade_candle['ATR']/trade.open_rate

                # sell when profit exceeds target
                if (current_profit > profit_target):
                    return 'take_profit'
```

**Comment by xmatthias** [comment]
it was my assumption that updating wouldn't fix the problem - but it's still better to use an uptodate version :)

Great that it could be fixed for you :+1:
